#pragma once

enum CommandCategory
{
    CATEGORY_DEBUG = 0x0,
    CATEGORY_GRAPHICS = 0x1,
    CATEGORY_CONSOLE = 0x2,
    CATEGORY_COMBAT = 0x3,
    CATEGORY_GAME = 0x4,
    CATEGORY_DEFAULT = 0x5,
    CATEGORY_NET = 0x6,
    CATEGORY_SOUND = 0x7,
    CATEGORY_GM = 0x8,
};